"""Configuration module for Disease Classification Framework"""

from .settings import (
    # Paths
    BASE_DIR,
    CKPT_DIR,
    PLOTS_DIR,
    METRICS_DIR,
    KFOLD_DIR,
    DEPLOY_DIR,
    SMOKE_CHECK_DIR,
    PRETRAINED_DIR,
    RAW_DIR,
    SPLIT_DIR,
    TRAIN_DIR,
    VAL_DIR,
    TEST_DIR,
    DEBUG_LOG_DIR,
    
    # Model config
    BACKBONES,
    IMG_SIZE,
    BATCH_SIZE,
    NUM_CLASSES,
    K_FOLDS,
    SEED,
    
    # Training config
    EPOCHS_HEAD,
    EPOCHS_FINETUNE,
    PATIENCE_HEAD,
    PATIENCE_FT,
    WEIGHT_DECAY,
    BACKBONE_LR,
    HEAD_LR,
    
    # Feature flags
    ENABLE_KFOLD_CV,
    ENABLE_EXPORT,
    ENABLE_TRANSFER_LEARNING,
    TRANSFER_LEARNING_MODE,
    
    # Export config
    EXPORT_TYPES,
    EXPORT_FORMATS,
    EXPORT_CONFIG,
    PRETRAINED_DOWNLOAD_MAP,
    PRETRAINED_PATHS,
    
    # Debug config
    DEBUG_MODE,
    DEBUG_BACKBONE,
    DEBUG_FUNCTION,
    DEBUG_FUNCTIONS,
    DEBUG_EPOCHS_HEAD,
    DEBUG_EPOCHS_FINETUNE,
    DEBUG_BATCH_SIZE,
    DEBUG_ENABLE_EXPORT,
)

__all__ = [
    'BASE_DIR', 'CKPT_DIR', 'PLOTS_DIR', 'METRICS_DIR', 'KFOLD_DIR',
    'DEPLOY_DIR', 'SMOKE_CHECK_DIR', 'PRETRAINED_DIR', 'RAW_DIR',
    'SPLIT_DIR', 'TRAIN_DIR', 'VAL_DIR', 'TEST_DIR', 'DEBUG_LOG_DIR',
    'BACKBONES', 'IMG_SIZE', 'BATCH_SIZE', 'NUM_CLASSES', 'K_FOLDS', 'SEED',
    'EPOCHS_HEAD', 'EPOCHS_FINETUNE', 'PATIENCE_HEAD', 'PATIENCE_FT',
    'WEIGHT_DECAY', 'BACKBONE_LR', 'HEAD_LR',
    'ENABLE_KFOLD_CV', 'ENABLE_EXPORT', 'ENABLE_TRANSFER_LEARNING',
    'TRANSFER_LEARNING_MODE', 'EXPORT_TYPES', 'EXPORT_FORMATS',
    'EXPORT_CONFIG', 'PRETRAINED_DOWNLOAD_MAP', 'PRETRAINED_PATHS',
    'DEBUG_MODE', 'DEBUG_BACKBONE', 'DEBUG_FUNCTION', 'DEBUG_FUNCTIONS',
    'DEBUG_EPOCHS_HEAD', 'DEBUG_EPOCHS_FINETUNE', 'DEBUG_BATCH_SIZE',
    'DEBUG_ENABLE_EXPORT',
]
